### ISSUE TITLE
Version 0.964 Conversion inserts "*" or did not remove a  ")" in perl conversion

### ISSUE THREAD

**Issue by pateshix** [snoopyjc/pythonizer#3]
plxcji019> Conv2portParams_hz_new.py QA_tttt_25_res.in
  File "Conv2portParams_hz_new.py", line 736
    s11[(len(s11)-1)+1] = _num(inLst[1])+_num(i()*)inLst[2]
                                                                             ^
SyntaxError: invalid syntax

plxcji019> Conv2portParams_hz_new.py QA_tttt_25_res.in
  File "Conv2portParams_hz_new.py", line 736
    s11[(len(s11)-1)+1] = _num(inLst[1])+_num(i()*)inLst[2]
                                                                             ^
SyntaxError: invalid syntax
ERROR STATISTICS:  W: 4

Q?:   Also: I did not use -s for import math sin() cos() Should I in this case ??

 [Softpano-W325]:  Debug flag is set to 3

LINE 3 [main-W8238]:  Skipped translating /usr/intel/pkgs/perl/5.26.1/lib64/5.26.1/Math/Complex.pm to python for use in use Math::Complex (use '-s' option to translate it (not recommended))

LINE 4 [main-W8238]:  Skipped translating /usr/intel/pkgs/perl/5.26.1/lib64/site_perl/x86_64-linux/File/Spec.pm to python for use in use File::Spec (use '-s' option to translate it (not recommended))

LINE 5 [main-W8238]:  Skipped translating /usr/intel/pkgs/perl/5.26.1/lib64/site_perl/x86_64-linux/Cwd.pm to python for use in use Cwd (use '-s' option to translate it (not recommended))

[COnv2portParams_hz_new.PlPY.txt](https://github.com/snoopyjc/pythonizer/files/8292659/COnv2portParams_hz_new.PlPY.txt)

**Comment by pateshix** [comment]
Joe Cool

Please suggest a manual fix in Python 3.8 in the meantime

**Comment by pateshix** [comment]
Manual Changes Proposed: 3-21-22

              #s11[(len(s11)-1)+1] = _num(inLst[1])+_num(i()*)inLst[2]
                s11[(len(s11)-1)+1] = complex ( _num(inLst[1]), _num(inLst[2]) )
                #s21[(len(s21)-1)+1] = _num(inLst[3])+_num(i()*)inLst[4]
                s21[(len(s21)-1)+1] = complex (__num(inLst[3]), _num(inLst[4])  )
                #s12[(len(s12)-1)+1] = _num(inLst[5])+_num(i()*)inLst[6]
                s12[(len(s12)-1)+1] = complex ( _num(inLst[5]), _num(inLst[6]) )
                #s22[(len(s22)-1)+1] = _num(inLst[7])+_num(i()*)inLst[8]
                s22[(len(s22)-1)+1] = complex (__num(inLst[7]), _num(inLst[8])  )
            else:
                #s11[(len(s11)-1)+1] = inLst[1]cos(pi*_num(inLst[2])/180.0)+_num(i()*)inLst[1]sin(pi*_num(inLst[2])/180.0)
                s11[(len(s11)-1)+1] = complex (inLst[1]cos(pi*_num(inLst[2])/180.0) , inLst[1]sin(pi*_num(inLst[2])/180.0)  )
                #s21[(len(s21)-1)+1] = inLst[3]cos(pi*_num(inLst[4])/180.0)+_num(i()*)inLst[3]sin(pi*_num(inLst[4])/180.0)
                s21[(len(s21)-1)+1] = complex (inLst[3]cos(pi*_num(inLst[4])/180.0) , inLst[3]sin(pi*_num(inLst[4])/180.0)  )
                #s12[(len(s12)-1)+1] = inLst[5]cos(pi*_num(inLst[6])/180.0)+_num(i()*)inLst[5]sin(pi*_num(inLst[6])/180.0)
                s12[(len(s12)-1)+1] = complex (inLst[5]cos(pi*_num(inLst[6])/180.0) , inLst[5]sin(pi*_num(inLst[6])/180.0)  )
                #s22[(len(s22)-1)+1] = inLst[7]cos(pi*_num(inLst[8])/180.0)+_num(i()*)inLst[7]sin(pi*_num(inLst[8])/180.0)
                s22[(len(s22)-1)+1] = complex (inLst[7]cos(pi*_num(inLst[8])/180.0) , inLst[7]sin(pi*_num(inLst[8])/180.0)  )

view Conv2portParams_hz_new.py
plxcji019> python3 -m pdb Conv2portParams_hz_new.py
Traceback (most recent call last):
  File "/usr/intel/pkgs/python3/3.8.2/lib/python3.8/pdb.py", line 1703, in main
    pdb._runscript(mainpyfile)
  File "/usr/intel/pkgs/python3/3.8.2/lib/python3.8/pdb.py", line 1572, in _runscript
    self.run(statement)
  File "/usr/intel/pkgs/python3/3.8.2/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/nfs/pdx/disks/x5e2d_circuit_simulation_gwa001/pateshix/conv_pl_py_1/Conv2portParams_hz_new.py", line 760
    s11[(len(s11)-1)+1] = complex (inLst[1]cos(pi*_num(inLst[2])/180.0) , inLst[1]sin(pi*_num(inLst[2])/180.0)  )
                                                                         ^


Second manual Change
Amplitude or magnitude of complex impedance at frequency (x)               - Guessing hueristic - multiply ? (*) ??

                                                          s11[(len(s11)-1)+1] = complex (inLst[1]*cos(pi*_num(inLst[2])/180.0) , inLst[1]*sin(pi*_num(inLst[2])/180.0)  )

or may need Second Guess::

Mag(inLst[1]),inLst[2] ) = sqrt ( inLst[1]) )^2 + (inLst[2])^2   )

**Comment by snoopyjc** [comment]
You probably need “import math” and “import cmath” and prefix the functions (sin/cos etc) with the appropriate library.  If the value is in the complex constructor, use math, and if it’s already a complex value, then use cmath.

**Comment by snoopyjc** [comment]
Oh and ^ is not power, you mean **

**Comment by pateshix** [comment]
Yes ** not ^ correct -

**Comment by pateshix** [comment]
# Got it – Thanks!
# I reconstructed the correct a*cos(x) + j*a*sin(x)  from the perl5 script in python3. So I have a manual workaround with
import math, cmath
#  and then
from math import sin, cos, sqrt

**Comment by snoopyjc** [comment]
Need to first add these core functions: exp, sin, cos, log

**Comment by snoopyjc** [comment]
Need to also convert this idiom to INF: 9**9**9

**Comment by snoopyjc** [comment]
Fixed in v0.966 - translated the Math::Complex module automatically into Python (with lots of bugs in Pythonizer fixed along the way and `wantarray` implemented)
